// Generated by CoffeeScript 1.6.1
var SiteBuilder, inspect, path, qutil,
  __slice = [].slice;

path = require('path');

qutil = require('./util');

inspect = require('util').inspect;

SiteBuilder = (function() {

  SiteBuilder.prototype.fsTaskQueue = qutil.taskQueue(35);

  function SiteBuilder(rootPath, contentTree) {
    this.contentTree = contentTree;
    this.rootPath = path.resolve(rootPath);
    this.cwd = path.resolve('.');
  }

  SiteBuilder.prototype.build = function(vars, doneBuildFn) {
    var dirTasks, fnList, logStarted, logUnchanged, rootOutput, tasks, tidUpdate, trackerMap,
      _this = this;
    if (typeof vars === 'function') {
      doneBuildFn = vars;
      vars = null;
    }
    rootOutput = Object.create(null, {
      rootPath: {
        value: this.rootPath,
        enumerable: true
      }
    });
    vars = Object.create(vars || null, {
      output: {
        value: rootOutput
      }
    });
    trackerMap = {};
    fnList = [];
    dirTasks = qutil.createTaskTracker(function() {
      _this.fsTaskQueue.extend(fnList);
      return fnList = null;
    });
    tidUpdate = setInterval(this.logTasksUpdate.bind(this, tasks, trackerMap), this.msTasksUpdate || 2000);
    tasks = qutil.createTaskTracker(function() {
      clearInterval(tidUpdate);
      return doneBuildFn();
    });
    logStarted = this.logStarted.bind(this);
    logUnchanged = this.logUnchanged.bind(this);
    return this.contentTree.visit(function(vkind, citem, keyPath) {
      var fullPath, output, relPath, rvars;
      relPath = keyPath.join('/');
      fullPath = path.resolve(_this.rootPath, relPath);
      if (vkind === 'tree') {
        _this.fs.makeDirs(fullPath, dirTasks());
      }
      if (citem.renderFn != null) {
        output = Object.create(rootOutput, {
          vkind: {
            value: vkind
          },
          relPath: {
            value: relPath,
            enumerable: true
          },
          fullPath: {
            value: fullPath
          },
          content: {
            value: citem
          }
        });
        rvars = Object.create(vars, {
          output: {
            value: output,
            enumerable: true
          }
        });
        fnList.push(function(taskDone) {
          return _this.fs.stat(output.fullPath, taskDone.wrap(function(err, stat) {
            var renderAnswer;
            if (stat != null) {
              output.mtime = stat.mtime;
              if ((citem.mtime != null) && citem.mtime > stat.mtime) {
                return logUnchanged(output);
              }
            }
            logStarted(output);
            renderAnswer = tasks(function() {
              delete trackerMap[relPath];
              return _this.renderAnswerEx.apply(_this, [output].concat(__slice.call(arguments)));
            });
            trackerMap[relPath] = renderAnswer;
            return citem.renderFn(rvars, renderAnswer);
          }));
        });
      }
      return true;
    });
  };

  SiteBuilder.prototype.fs = qutil.fs;

  SiteBuilder.prototype.renderAnswerEx = function(rx, err, what) {
    var mtime, _ref,
      _this = this;
    if ((err != null) && !this.logError(err, rx)) {
      return;
    }
    if (what != null) {
      mtime = (_ref = rx.content) != null ? _ref.mtime : void 0;
      if ((mtime != null) && rx.mtime && mtime <= rx.mtime) {
        this.logUnchanged(rx);
      } else {
        this.fsTaskQueue["do"](function() {
          if (what.pipe != null) {
            what.pipe(_this.fs.createWriteStream(rx.fullPath));
          } else {
            _this.fs.writeFile(rx.fullPath, what);
          }
          return _this.logChanged(rx);
        });
      }
    }
  };

  SiteBuilder.prototype.logPathsFor = function(rx) {
    var _ref, _ref1;
    return {
      dst: path.relative(this.cwd, rx.relPath),
      src: path.relative(this.cwd, ((_ref = rx.content) != null ? (_ref1 = _ref.entry) != null ? _ref1.srcPath : void 0 : void 0) || rx.relPath)
    };
  };

  SiteBuilder.prototype.logStarted = function(rx) {};

  SiteBuilder.prototype.logError = function(err, rx) {
    var paths;
    paths = this.logPathsFor(rx);
    console.error("ERROR['" + paths.src + "'] :: " + err);
  };

  SiteBuilder.prototype.logChanged = function(rx) {
    var paths;
    paths = this.logPathsFor(rx);
    console.error("WRITE['" + paths.src + "'] -- '" + paths.dst + "'");
  };

  SiteBuilder.prototype.logUnchanged = function(rx) {};

  SiteBuilder.prototype.logTasksUpdate = function(tasks, trackerMap) {
    return console.warn("tasks active: " + tasks.active + " waiting on: " + (inspect(Object.keys(trackerMap))));
  };

  return SiteBuilder;

})();

exports.SiteBuilder = SiteBuilder;

exports.createBuilder = function(rootPath, content) {
  return new SiteBuilder(rootPath, content);
};
