// Generated by CoffeeScript 1.4.0
var SiteBuilder, inspect, path, qutil,
  __slice = [].slice;

path = require('path');

qutil = require('./util');

inspect = require('util').inspect;

SiteBuilder = (function() {

  function SiteBuilder(rootPath, contentTree) {
    this.contentTree = contentTree;
    this.rootPath = path.resolve(rootPath);
    this.cwd = path.resolve('.');
  }

  SiteBuilder.prototype.build = function(vars, done) {
    var dirTasks, fnList, logStarted, rootOutput, rootPath, tasks, tidUpdate, tq, trackerMap,
      _this = this;
    if (typeof vars === 'function') {
      done = vars;
      vars = null;
    }
    rootPath = this.rootPath;
    rootOutput = Object.create(null, {
      rootPath: {
        value: this.rootPath,
        enumerable: true
      }
    });
    vars = Object.create(vars || null, {
      output: {
        value: rootOutput
      }
    });
    trackerMap = {};
    fnList = [];
    tq = qutil.taskQueue(this.limit);
    dirTasks = qutil.createTaskTracker(function() {
      tq.extend(fnList);
      return fnList = null;
    });
    tasks = qutil.createTaskTracker(function() {
      clearInterval(tidUpdate);
      return done();
    });
    tidUpdate = setInterval(function() {
      return console.warn("tasks active: " + tasks.active + " waiting on: " + (inspect(Object.keys(trackerMap))));
    }, 2000);
    logStarted = this.logStarted.bind(this);
    return this.contentTree.visit(function(vkind, contentItem, keyPath) {
      var fullPath, objVars, output, relPath, renderAnswer;
      if (!(contentItem.renderFn != null)) {
        return true;
      }
      relPath = keyPath.join('/');
      fullPath = path.resolve(_this.rootPath, relPath);
      if (vkind === 'tree') {
        _this.fs.makeDirs(fullPath, dirTasks());
      }
      output = Object.create(rootOutput, {
        vkind: {
          value: vkind
        },
        relPath: {
          value: relPath,
          enumerable: true
        },
        fullPath: {
          value: fullPath
        },
        contentItem: {
          value: contentItem
        }
      });
      objVars = Object.create(vars, {
        output: {
          value: output,
          enumerable: true
        }
      });
      renderAnswer = tasks(function() {
        delete trackerMap[relPath];
        return _this.renderAnswerEx.apply(_this, [output].concat(__slice.call(arguments)));
      });
      trackerMap[relPath] = renderAnswer;
      fnList.push(function(taskDone) {
        return _this.fs.stat(output.fullPath, taskDone.wrap(function(err, stat) {
          if (stat != null) {
            output.mtime = stat.mtime;
          }
          logStarted(output);
          return contentItem.renderFn(objVars, renderAnswer);
        }));
      });
      return true;
    });
  };

  SiteBuilder.prototype.fs = qutil.fs;

  SiteBuilder.prototype.renderAnswerEx = function(rx, err, what) {
    var mtime, _ref, _ref1;
    if ((err != null) && !this.logError(err, rx)) {
      return;
    }
    if (what != null) {
      mtime = (_ref = rx.contentItem) != null ? (_ref1 = _ref.entry) != null ? _ref1.mtime : void 0 : void 0;
      if ((mtime != null) && rx.mtime && mtime <= rx.mtime) {
        this.logUnchanged(rx);
      } else {
        if (what.pipe != null) {
          what.pipe(this.fs.createWriteStream(rx.fullPath));
        } else {
          this.fs.writeFile(rx.fullPath, what);
        }
        this.logChanged(rx);
      }
    }
  };

  SiteBuilder.prototype.logStarted = function(rx) {};

  SiteBuilder.prototype.logError = function(err, rx) {
    console.error("ERROR['" + (path.relative(this.cwd, rx.fullPath)) + "'] :: " + err);
  };

  SiteBuilder.prototype.logChanged = function(rx) {
    console.error("WRITE['" + (path.relative(this.cwd, rx.fullPath)) + "']");
  };

  SiteBuilder.prototype.logUnchanged = function(rx) {};

  return SiteBuilder;

})();

exports.SiteBuilder = SiteBuilder;
