// Generated by CoffeeScript 1.6.1
var ContentBaseNode, ContentCollectionMixin, ContentComposite, ContentItem, ContentRoot, ContentTree, CtxTree, Renderable, invokeList,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

invokeList = require('./util').invokeList;

Renderable = (function() {

  function Renderable() {}

  Renderable.prototype.bindRender = function(entry) {
    if (entry != null) {
      this.render = this.renderEntryFn.bind(this, entry);
    }
    return this.renderTasks();
  };

  Renderable.prototype.renderTasks = function() {
    var tasks;
    if ((tasks = this._renderTasks) == null) {
      tasks = invokeList.ordered();
      this._renderTasks = tasks;
    }
    return tasks;
  };

  Renderable.prototype.addTemplate = function(tmplFn, order) {
    var tasks;
    if (typeof tmplFn !== 'function') {
      throw new Error("Content template must be a function");
    }
    tasks = this.renderTasks();
    if (tasks.tmpl == null) {
      tasks.tmpl = invokeList.ordered();
      tasks.add(1.0, this.renderTemplateFn.bind(this, tasks.tmpl));
    }
    tasks.tmpl.add(order, tmplFn);
    return this;
  };

  Renderable.prototype.renderTemplateFn = function(templates, source, vars, answerFn) {
    var tmplFn;
    tmplFn = templates.sort().slice(-1).pop();
    vars = Object.create(vars, {
      content: {
        value: source
      }
    });
    return tmplFn(vars, answerFn);
  };

  Renderable.prototype.extendVars = function(vars) {
    if (vars == null) {
      vars = {};
    }
    return Object.create(vars, {
      ctx: {
        value: this.ctx
      },
      meta: {
        value: this.meta
      }
    });
  };

  Renderable.prototype.renderEntryFn = function(entry, vars, answerFn) {
    var stepFn, _ref;
    try {
      if (this._renderTasks.length > 0) {
        vars = this.extendVars(vars);
        stepFn = this._renderTasks.iter(function(renderFn, err, src) {
          if ((err == null) && renderFn !== void 0) {
            return renderFn(src, vars, stepFn);
          } else {
            return answerFn(err, src);
          }
        });
        return entry.read(stepFn);
      } else {
        this.touch((_ref = entry.stat) != null ? _ref.mtime : void 0);
        return answerFn(null, entry.readStream());
      }
    } catch (err) {
      return answerFn(err);
    }
  };

  return Renderable;

})();

ContentBaseNode = (function(_super) {

  __extends(ContentBaseNode, _super);

  function ContentBaseNode() {
    return ContentBaseNode.__super__.constructor.apply(this, arguments);
  }

  Object.defineProperties(ContentBaseNode.prototype, {
    dependencies: {
      get: function() {
        return this.deps;
      }
    },
    deps: {
      get: function() {
        return this.deps = [];
      }
    }
  });

  ContentBaseNode.prototype.isContentNode = true;

  ContentBaseNode.prototype.init = function(container) {
    this.meta = {};
    return this.ctx = this.initCtx(container != null ? container.ctx : void 0);
  };

  ContentBaseNode.prototype.initCtx = function(ctx_next) {
    return ctx_next || {};
  };

  ContentBaseNode.prototype.pushCtx = function(ctx_next) {
    var tmpl;
    tmpl = (ctx_next != null) && Object.create(ctx_next.tmpl) || {};
    return Object.create(ctx_next || null, {
      tmpl: {
        value: tmpl
      },
      ctx_next: {
        value: ctx_next
      }
    });
  };

  ContentBaseNode.prototype.visit = function(visitor, keyPath) {
    throw new Error("Subclass responsibility: " + this.constructor.name + "::visit()");
  };

  ContentBaseNode.prototype.compositeWith = function(key, contentItem, container) {
    var comp;
    comp = new ContentComposite(container, key);
    comp.addItem(this.key, this);
    comp.addItem(key, contentItem);
    return comp;
  };

  ContentBaseNode.prototype.touch = function(arg) {
    if (arg == null) {
      arg = true;
    }
    if (arg === 0) {
      delete this.mtime;
    } else if (arg === true) {
      this.mtime = new Date();
    } else {
      arg = Math.max(this.mtime || 0, arg || 0);
      this.mtime = new Date(arg);
    }
    return this.mtime;
  };

  return ContentBaseNode;

})(Renderable);

ContentItem = (function(_super) {

  __extends(ContentItem, _super);

  ContentItem.prototype.kind = 'item';

  function ContentItem(container, key) {
    this.key = key;
    this.init(container);
  }

  ContentItem.prototype.initCtx = function(ctx_next) {
    return ctx_next;
  };

  ContentItem.prototype.visit = function(visitor, keyPath) {
    if (keyPath == null) {
      keyPath = [];
    }
    return visitor(this.kind, this, keyPath.concat([this.key]));
  };

  return ContentItem;

})(ContentBaseNode);

ContentComposite = (function(_super) {

  __extends(ContentComposite, _super);

  ContentComposite.prototype.kind = 'composite';

  function ContentComposite(container, key) {
    this.key = key;
    this.list = [];
    this.init(container);
  }

  ContentComposite.prototype.addItem = function(key, item) {
    if (!item.isContentNode) {
      throw new Error("Can only add ContentItem objects");
    }
    this.list.push(item);
    return item;
  };

  ContentComposite.prototype.compositeWith = function(key, contentItem, container) {
    this.list.push(contentItem);
    return this;
  };

  ContentComposite.prototype.visit = function(visitor, keyPath) {
    var res;
    if (keyPath == null) {
      keyPath = [];
    }
    res = visitor(this.kind, this, keyPath.slice());
    if (res === false) {

    } else {
      return this.visitList(visitor, keyPath);
    }
  };

  ContentComposite.prototype.visitList = function(visitor, keyPath) {
    var each, _i, _len, _ref;
    if (keyPath == null) {
      keyPath = [];
    }
    _ref = this.list;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      each = _ref[_i];
      each.visit(visitor, keyPath);
    }
    return true;
  };

  return ContentComposite;

})(ContentBaseNode);

ContentRoot = (function(_super) {

  __extends(ContentRoot, _super);

  ContentRoot.prototype.kind = 'root';

  function ContentRoot(key) {
    ContentRoot.__super__.constructor.call(this, null, key);
  }

  return ContentRoot;

})(ContentComposite);

ContentTree = (function(_super) {

  __extends(ContentTree, _super);

  ContentTree.prototype.kind = 'tree';

  function ContentTree(container, key) {
    this.key = key;
    this.items = {};
    this.init(container);
    if (!this.key) {
      throw new Error("Key must be valid " + this);
    }
  }

  ContentTree.prototype.addItem = function(key, item) {
    var curItem;
    if (!item.isContentNode) {
      throw new Error("Can only add ContentNode objects");
    }
    if ((curItem = this.items[key]) != null) {
      item = curItem.compositeWith(key, item, this);
    }
    this.items[key] = item;
    return item;
  };

  ContentTree.prototype.getItem = function(key) {
    return this.items[key];
  };

  ContentTree.prototype.visit = function(visitor, keyPath) {
    var res;
    if (keyPath == null) {
      keyPath = [];
    }
    keyPath = keyPath.concat([this.key]);
    res = visitor(this.kind, this, keyPath.slice());
    if (res === false) {

    } else {
      return this.visitItems(visitor, keyPath);
    }
  };

  ContentTree.prototype.visitItems = function(visitor, keyPath) {
    var each, key, _ref;
    if (keyPath == null) {
      keyPath = [];
    }
    _ref = this.items;
    for (key in _ref) {
      each = _ref[key];
      each.visit(visitor, keyPath);
    }
    return true;
  };

  return ContentTree;

})(ContentBaseNode);

CtxTree = (function(_super) {

  __extends(CtxTree, _super);

  function CtxTree() {
    return CtxTree.__super__.constructor.apply(this, arguments);
  }

  CtxTree.prototype.kind = 'ctx_tree';

  CtxTree.prototype.isCtxTree = true;

  CtxTree.prototype.initCtx = function(ctx_parent) {
    var ctx;
    if (ctx_parent != null) {
      ctx = this.pushCtx(ctx_parent[this.key]);
      return ctx_parent[this.key] = ctx;
    } else {
      return {};
    }
  };

  CtxTree.prototype.adaptMatchKind = function(matchKind) {
    return 'context';
  };

  return CtxTree;

})(ContentTree);

ContentCollectionMixin = (function() {

  function ContentCollectionMixin() {}

  ContentCollectionMixin.prototype.ContentItem = ContentItem;

  ContentCollectionMixin.prototype.ContentTree = ContentTree;

  ContentCollectionMixin.prototype.CtxTree = CtxTree;

  ContentCollectionMixin.prototype.initCtx = function(ctx_next) {
    return this.pushCtx(ctx_next);
  };

  ContentCollectionMixin.prototype.newContentEx = function(container, key) {
    return new this.ContentItem(container, key);
  };

  ContentCollectionMixin.prototype.newContent = function(key) {
    return this.newContentEx(this, key);
  };

  ContentCollectionMixin.prototype.addContent = function(key) {
    return this.addItem(key, this.newContentEx(this, key));
  };

  ContentCollectionMixin.prototype.getContent = function(key) {
    var item;
    if ((item = typeof this.getItem === "function" ? this.getItem(key) : void 0) == null) {
      item = this.addContent(key);
    }
    return item;
  };

  ContentCollectionMixin.prototype.newTreeEx = function(container, key) {
    return new this.ContentTree(container, key);
  };

  ContentCollectionMixin.prototype.newTree = function(key) {
    return this.newTreeEx(this, key);
  };

  ContentCollectionMixin.prototype.addTree = function(key) {
    return this.addItem(key, this.newTreeEx(this, key));
  };

  ContentCollectionMixin.prototype.newCtxTreeEx = function(container, key) {
    return new this.CtxTree(container, key);
  };

  ContentCollectionMixin.prototype.newCtxTree = function(key) {
    return this.newCtxTreeEx(this, key);
  };

  ContentCollectionMixin.mixInto = function(tgtClass) {
    var k, tgt, v, _ref;
    tgt = tgtClass.prototype || tgtClass;
    _ref = this.prototype;
    for (k in _ref) {
      v = _ref[k];
      tgt[k] = v;
    }
  };

  return ContentCollectionMixin;

})();

ContentCollectionMixin.mixInto(ContentTree);

ContentCollectionMixin.mixInto(ContentComposite);

module.exports = {
  ContentBaseNode: ContentBaseNode,
  ContentCollectionMixin: ContentCollectionMixin,
  ContentItem: ContentItem,
  ContentTree: ContentTree,
  ContentRoot: ContentRoot,
  createRoot: function() {
    return new ContentRoot();
  }
};
