//@ sourceMappingURL=entry.map
// Generated by CoffeeScript 1.6.1
var MatchEntry, MatchingWalker, stream, tromp,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __slice = [].slice;

stream = require('stream');

tromp = require('tromp');

MatchEntry = (function() {

  Object.defineProperties(MatchEntry.prototype, {
    srcName: {
      get: function() {
        return this.src.name;
      }
    },
    srcPath: {
      get: function() {
        return this.src.path;
      }
    },
    srcRelPath: {
      get: function() {
        return this.src.relPath;
      }
    },
    mode: {
      get: function() {
        return this.src.mode;
      }
    },
    stat: {
      get: function() {
        return this.src.stat;
      }
    },
    path: {
      get: function() {
        return this.src.node.resolve(this.name);
      }
    },
    relPath: {
      get: function() {
        return this.src.node.relative(this.path);
      }
    },
    rootPath: {
      get: function() {
        return this.src.node.rootPath;
      }
    },
    parentEntry: {
      get: function() {
        return this.src.node.entry;
      }
    },
    ctx: {
      get: function() {
        var _ref;
        return ((_ref = this.content) != null ? _ref.ctx : void 0) || this.baseTree.ctx;
      }
    },
    name: {
      get: function() {
        var ext;
        ext = this.ext.join('.');
        return this.name0 + (ext && "." + ext || '');
      }
    }
  });

  MatchEntry.prototype.isFile = function() {
    return this.src.isFile();
  };

  MatchEntry.prototype.isDirectory = function() {
    return this.src.isDirectory();
  };

  function MatchEntry(walkEntry, baseTree, pluginMap) {
    this.ext = walkEntry.name.split('.');
    this.name0 = this.ext.shift();
    Object.defineProperties(this, {
      src: {
        value: walkEntry
      },
      srcExt: {
        value: this.ext.slice()
      },
      baseTree: {
        value: baseTree
      },
      pluginMap: {
        value: pluginMap
      }
    });
  }

  MatchEntry.prototype.setMatchMethod = function(matchKind) {
    if (this.baseTree.adaptMatchKind != null) {
      matchKind = this.baseTree.adaptMatchKind(matchKind, entry);
    }
    if (this.isDirectory()) {
      return this.matchMethod = matchKind + 'Dir';
    } else {
      return this.matchMethod = matchKind;
    }
  };

  MatchEntry.prototype.toJSON = function() {
    return {
      path: this.relPath,
      src: {
        path: this.relPath,
        mode: this.mode
      }
    };
  };

  MatchEntry.prototype.inspect = function() {
    return "[" + this.constructor.name + " " + this.mode + ":'" + this.relPath + "' src:'" + this.srcRelPath + "']";
  };

  MatchEntry.prototype.toString = function() {
    return this.inspect();
  };

  MatchEntry.prototype.walk = function() {
    if (this.src.isWalkable()) {
      return this.src.node.root.walk(this, this.src.node.target);
    }
  };

  MatchEntry.prototype.isWalkable = function() {
    var _ref;
    return (_ref = this.src).isWalkable.apply(_ref, arguments);
  };

  MatchEntry.prototype.walkPath = function() {
    return this.src.path;
  };

  MatchEntry.prototype.setCtxValue = function(value) {
    if (value !== void 0) {
      return this.ctx[this.name0] = value;
    }
  };

  MatchEntry.prototype.setCtxTemplate = function(tmplFn) {
    if (typeof tmplFn === 'function') {
      return this.ctx.tmpl[this.name0] = tmplFn;
    } else if (tmplFn !== void 0) {
      throw new Error("setCtxTemplate must be called with a template function ");
    }
  };

  MatchEntry.prototype._setContent = function(content, tree) {
    if (tree != null) {
      Object.defineProperty(content, 'tree', {
        value: tree
      });
    }
    Object.defineProperty(this, 'content', {
      value: content,
      enumerable: true
    });
    return content;
  };

  MatchEntry.prototype.newCtxTree = function(key) {
    var tree;
    if (key == null) {
      key = this.name;
    }
    tree = this.baseTree.newTree(key);
    return this._setContent(tree, tree);
  };

  MatchEntry.prototype.addContentTree = function(key) {
    var tree;
    if (key == null) {
      key = this.name;
    }
    tree = this.baseTree.addTree(key);
    return this._setContent(tree, tree);
  };

  MatchEntry.prototype.addComposite = function(key, childKey) {
    var citem, tree;
    if (key == null) {
      key = this.name;
    }
    tree = this.baseTree.newTree(key);
    citem = tree.getContent(childKey || key);
    this.baseTree.addItem(key, citem);
    return this._setContent(citem, tree);
  };

  MatchEntry.prototype.getContent = function(key) {
    if (key == null) {
      key = this.name;
    }
    if (this.content != null) {
      return this.content;
    }
    return this._setContent(this.baseTree.getContent(key));
  };

  MatchEntry.prototype.bindContent = function(key) {
    var content;
    if (key == null) {
      key = this.name;
    }
    content = this.getContent(this.name);
    content.updateMetaFromEntry(this);
    return content;
  };

  MatchEntry.prototype.getWalkContentTree = function() {
    var _ref;
    return ((_ref = this.content) != null ? _ref.tree : void 0) || this.baseTree;
  };

  MatchEntry.prototype.fs = require('fs');

  MatchEntry.prototype.readStream = function(options) {
    if (this.isFile) {
      return this.fs.createReadStream(this.src.path, options);
    }
  };

  MatchEntry.prototype.read = function(encoding, callback) {
    if (encoding == null) {
      encoding = 'utf-8';
    }
    if (typeof encoding === 'function') {
      callback = encoding;
      encoding = 'utf-8';
    }
    if (this.isFile) {
      this.fs.readFile(this.src.path, encoding, callback);
    }
  };

  MatchEntry.prototype.readSync = function(encoding) {
    if (encoding == null) {
      encoding = 'utf-8';
    }
    if (this.isFile) {
      return this.fs.readFileSync(this.src.path, encoding);
    }
  };

  MatchEntry.prototype.loadModule = function() {
    return require(this.src.path);
  };

  return MatchEntry;

})();

exports.MatchEntry = MatchEntry;

MatchingWalker = (function(_super) {

  __extends(MatchingWalker, _super);

  function MatchingWalker(site, ruleset, history) {
    this.site = site;
    this.ruleset = ruleset;
    this.history = history != null ? history : {};
    MatchingWalker.__super__.constructor.call(this, {
      autoWalk: false
    });
    Object.defineProperty(this, '_self_', {
      value: this
    });
  }

  MatchingWalker.prototype.instance = function(baseTree, pluginMap) {
    return Object.create(this._self_, {
      baseTree: {
        value: baseTree
      },
      pluginMap: {
        value: pluginMap || this.pluginMap
      }
    });
  };

  MatchingWalker.prototype.walkListing = function(listing) {
    var entry, _ref;
    if ((_ref = (entry = listing.node.entry)) != null ? _ref.isDirectory() : void 0) {
      return this.instance(entry.getWalkContentTree(), entry.pluginMap);
    }
    return this;
  };

  MatchingWalker.prototype.walkRootContent = function(aPath, baseTree, pluginMap) {
    return this.instance(baseTree, pluginMap).walk(aPath);
  };

  MatchingWalker.prototype.walkNotify = function() {
    var args, op, _ref;
    op = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return (_ref = this["_op_" + op]) != null ? _ref.apply(this, args) : void 0;
  };

  MatchingWalker.prototype._op_listing_pre = function(listing) {
    var c;
    c = this.history[listing.path] || 0;
    return this.history[listing.path] = c + 1;
  };

  MatchingWalker.prototype._op_dir = function(entry) {
    var c;
    c = this.history[entry.path] || 0;
    entry = new MatchEntry(entry, this.baseTree, this.pluginMap);
    if (c === 0 || this.site.rewalkEntry(entry, c)) {
      this.history[entry.path] = c + 1;
      return this.ruleset.matchRules(entry, this);
    }
  };

  MatchingWalker.prototype._op_file = function(entry) {
    entry = new MatchEntry(entry, this.baseTree, this.pluginMap);
    return this.ruleset.matchRules(entry, this);
  };

  MatchingWalker.prototype.match = function(entry, matchKind) {
    var matchMethod, plugin;
    try {
      matchMethod = entry.setMatchMethod(matchKind);
      plugin = this.pluginMap.findPlugin(entry);
      if (plugin == null) {
        return this.site.matchEntryNullPlugin(entry);
      } else {
        return this.site.matchEntryPlugin(entry, plugin.bindPluginFn(matchMethod), plugin);
      }
    } catch (err) {
      console.warn(entry);
      console.warn(err.stack || err);
      return console.warn('');
    }
  };

  return MatchingWalker;

})(tromp.WalkRoot);

exports.MatchingWalker = MatchingWalker;

exports.createWalker = function(site, ruleset) {
  return new MatchingWalker(site, ruleset);
};
