// Generated by CoffeeScript 1.6.1
var PipelinePlugin, PluginBaseMap, exports;

PipelinePlugin = require('./pluginTypes').PipelinePlugin;

PluginBaseMap = (function() {

  function PluginBaseMap() {
    Object.defineProperties(this, {
      db: {
        value: {}
      }
    });
  }

  PluginBaseMap.prototype.inspect = function() {
    return "«" + this.constructor.name + "»";
  };

  PluginBaseMap.prototype.toString = function() {
    return this.inspect();
  };

  PluginBaseMap.prototype.invalidate = function() {
    this._cache = {};
    return this;
  };

  PluginBaseMap.prototype.reset = function() {
    this.db = {};
    return this.invalidate();
  };

  PluginBaseMap.prototype.clone = function() {
    var self;
    self = Object.create(this, {
      db: {
        value: Object.create(this.db)
      }
    });
    return self.invalidate();
  };

  PluginBaseMap.prototype.freeze = function(deep) {
    var hash;
    if (deep == null) {
      deep = true;
    }
    this.exportPluginsTo(hash = {}, deep);
    return this.reset().merge(hash);
  };

  PluginBaseMap.prototype.exportPluginsTo = function(tgt, deep) {
    var db, key, pi;
    db = this.db;
    for (key in db) {
      pi = db[key];
      if (deep || Object.hasOwnProperty(db, key)) {
        tgt[key] = pi;
      }
    }
    return tgt;
  };

  PluginBaseMap.prototype.merge = function(plugins) {
    var hash;
    if (plugins === true) {
      return this.freeze();
    } else if (plugins === false) {
      return this.reset();
    } else {
      if (plugins.exportPluginsTo != null) {
        plugins.exportPluginsTo(hash = {});
      } else {
        hash = plugins;
      }
      this.addPluginHash(hash);
    }
    return this.invalidate();
  };

  PluginBaseMap.prototype.addPluginHash = function(hash, deep) {
    var key, pi;
    for (key in hash) {
      pi = hash[key];
      if (deep || Object.hasOwnProperty(hash, key)) {
        if (this.acceptPlugin(key, pi)) {
          this.db[key] = pi;
        }
      }
    }
    return this.invalidate();
  };

  PluginBaseMap.prototype.addPluginAt = function(key, pi) {
    if (this.acceptPlugin(key, pi)) {
      this.db[key] = pi;
    }
    return this.invalidate();
  };

  PluginBaseMap.prototype.acceptPlugin = function(key, pi) {
    if (key[0] === '&') {
      return pi.isKindPlugin;
    } else {
      return pi.isFilePlugin;
    }
  };

  PluginBaseMap.prototype.findPluginListForExt = function(ext, entry) {
    var pi_list;
    if ((pi_list = this._cache[ext]) == null) {
      this._cache[ext] = pi_list = this._findPluginListForExt(ext, entry);
    }
    return pi_list.slice();
  };

  PluginBaseMap.prototype["default"] = function() {
    return this.db[''];
  };

  PluginBaseMap.prototype._findPluginListForExt = function(ext, entry) {
    var i, n, pi, pi_list;
    n = ext.length;
    if (n === 0) {
      return [this.db['']];
    }
    pi = this.db[ext[n - 1]];
    if (n === 1) {
      return [pi || this["default"]()];
    }
    pi_list = (function() {
      var _i, _ref, _results;
      _results = [];
      for (i = _i = _ref = n - 2; _ref <= 0 ? _i <= 0 : _i >= 0; i = _ref <= 0 ? ++_i : --_i) {
        _results.push(this._lookupPair(ext[i], ext[i + 1]));
      }
      return _results;
    }).call(this);
    pi_list[0] || (pi_list[0] = pi);
    i = pi_list.indexOf(void 0);
    if (~i) {
      pi_list.splice(i);
    }
    if (pi_list.length === 0) {
      pi_list.push(this["default"]());
    }
    return pi_list;
  };

  PluginBaseMap.prototype._lookupPair = function(fmt, ext) {
    return this.db[[fmt, ext]] || this.db[[fmt, '*']] || this.db[['*', ext]];
  };

  PluginBaseMap.prototype.findPluginForKind = function(kind0, entry) {
    var pi_kind;
    if (kind0 != null) {
      pi_kind = this.db['&' + kind0];
      if ((pi_kind == null) && kind0.match(/\D/)) {
        console.warn("Plugin for kind '" + entry.kind0 + "' not found. (re: " + entry.srcRelPath + ")");
      }
      if (pi_kind != null) {
        return pi_kind;
      }
    }
    return this.db['&'];
  };

  PluginBaseMap.prototype.findPlugin = function(entry) {
    var pi_kind, pi_list;
    if (!entry.isDirectory()) {
      pi_list = this.findPluginListForExt(entry.ext, entry);
    }
    pi_kind = this.findPluginForKind(entry.kind0, entry);
    return pi_kind.composePlugin(pi_list, entry);
  };

  return PluginBaseMap;

})();

module.exports = exports = {
  PluginBaseMap: PluginBaseMap
};
