// Generated by CoffeeScript 1.6.1
var BasicPlugin, CombinedPluginBase, CommonPluginBase, CompileRenderPlugin, CompiledPlugin, DirPluginBase, FilePluginBase, JsonPlugin, ModulePlugin, PipelinePlugin, RenderedPlugin, StaticPlugin, exports, makeRefError, pluginTypes, qpluginKinds, splitExt,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __slice = [].slice;

qpluginKinds = require('./pluginKinds');

module.exports = exports = Object.create(qpluginKinds);

pluginTypes = exports.pluginTypes;

exports.splitExt = splitExt = function(ext) {
  if (ext.split != null) {
    ext = ext.split(/[. ;,]+/);
  }
  if (!ext[0]) {
    ext.shift();
  }
  if (!ext[ext.length - 1]) {
    ext.pop();
  }
  return ext;
};

makeRefError = function(key) {
  return {
    get: function() {
      throw new Error("Reference '" + key + "' instead");
    },
    set: function() {
      throw new Error("Reference '" + key + "' instead");
    }
  };
};

CommonPluginBase = (function() {

  function CommonPluginBase() {}

  Object.defineProperties(CommonPluginBase.prototype, {
    pluginName: {
      get: function() {
        return this.name || this.constructor.name;
      }
    },
    inputs: makeRefError('input'),
    outputs: makeRefError('output')
  });

  CommonPluginBase.prototype.registerPluginOn = function(pluginMap) {
    throw new Error("Subclass responsibility (" + this.constructor.name + ")");
  };

  CommonPluginBase.prototype.init = function(opt) {
    if (opt != null) {
      return this.initOptions(opt);
    }
  };

  CommonPluginBase.prototype.initOptions = function(opt) {
    var k, v;
    if (opt != null) {
      for (k in opt) {
        if (!__hasProp.call(opt, k)) continue;
        v = opt[k];
        this[k] = v;
      }
    }
    return this;
  };

  CommonPluginBase.prototype.isPlugin = true;

  CommonPluginBase.prototype.inspect = function() {
    if (this.input != null) {
      return "«" + this.pluginName + " '" + this.input + "'»";
    } else {
      return "«" + this.pluginName + "»";
    }
  };

  CommonPluginBase.prototype.toString = function() {
    return this.inspect();
  };

  CommonPluginBase.prototype.splitExt = splitExt;

  CommonPluginBase.prototype.notImplemented = function(protocolMethod, entry, callback) {
    var err;
    err = "" + this + "::" + protocolMethod + "() not implemented for {entry: '" + entry.srcRelPath + "'}";
    callback(new Error(err));
  };

  CommonPluginBase.prototype.pluginProtocol = ['adapt', 'rename', 'render', 'context', 'bindRender', 'bindContext', 'bindTemplate'];

  CommonPluginBase.prototype.adapt = function(entry) {
    return this;
  };

  CommonPluginBase.prototype.rename = function(entry) {
    return entry;
  };

  CommonPluginBase.prototype.render = function(entry, vars, answerFn) {
    return this.notImplemented('render', entry, answerFn);
  };

  CommonPluginBase.prototype.bindRender = function(entry, callback) {
    var citem;
    citem = entry.getContent();
    citem.renderFn = this.render.bind(entry);
    return callback(null, citem);
  };

  CommonPluginBase.prototype.context = function(entry, callback) {
    return this.notImplemented('context', entry, callback);
  };

  CommonPluginBase.prototype.bindContext = function(entry, callback) {
    return this.context(entry, function(err, value) {
      if (!(value === void 0)) {
        entry.ctx[entry.name0] = value;
      }
      return callback(err, value);
    });
  };

  CommonPluginBase.prototype.bindTemplate = function(entry, callback, prefix) {
    return this.context(entry, function(err, value) {
      var citem;
      if (err != null) {
        return callback(err);
      }
      if (!(typeof value === 'function')) {
        err = new Error("" + this + " failed to create template function from " + entry);
        return callback(err, value);
      }
      if (prefix === false) {
        citem = entry.getContent();
        citem.templateFn = value;
        return callback(null, citem);
      } else {
        entry.ctx[prefix + entry.name0] = value;
        return callback(null, value);
      }
    });
  };

  return CommonPluginBase;

})();

DirPluginBase = (function(_super) {

  __extends(DirPluginBase, _super);

  function DirPluginBase() {
    return DirPluginBase.__super__.constructor.apply(this, arguments);
  }

  DirPluginBase.prototype.isDirPlugin = true;

  DirPluginBase.prototype.pluginProtocol = CommonPluginBase.prototype.pluginProtocol.concat(['contentDir', 'compositeDir', 'contextDir']);

  DirPluginBase.prototype.contentDir = function(entry, callback) {
    var ctree;
    ctree = entry.addContentTree();
    callback(null, ctree);
    return entry.walk();
  };

  DirPluginBase.prototype.compositeDir = function(entry, callback) {
    var ctree;
    ctree = entry.addComposite();
    callback(null, ctree);
    return entry.walk();
  };

  DirPluginBase.prototype.contextDir = function(entry, callback) {
    var ctree;
    if (entry.ext.length > 0) {
      console.warn('Context directories with extensions are not defined');
    }
    ctree = entry.newCtxTree();
    entry.walk();
    return callback(null, ctree);
  };

  return DirPluginBase;

})(CommonPluginBase);

FilePluginBase = (function(_super) {

  __extends(FilePluginBase, _super);

  function FilePluginBase() {
    return FilePluginBase.__super__.constructor.apply(this, arguments);
  }

  FilePluginBase.prototype.isFilePlugin = true;

  return FilePluginBase;

})(CommonPluginBase);

CombinedPluginBase = (function(_super) {

  __extends(CombinedPluginBase, _super);

  function CombinedPluginBase() {
    return CombinedPluginBase.__super__.constructor.apply(this, arguments);
  }

  CombinedPluginBase.prototype.isFilePlugin = true;

  return CombinedPluginBase;

})(DirPluginBase);

exports.CommonPluginBase = CommonPluginBase;

exports.DirPluginBase = DirPluginBase;

exports.FilePluginBase = FilePluginBase;

exports.CombinedPluginBase = CombinedPluginBase;

BasicPlugin = (function(_super) {

  __extends(BasicPlugin, _super);

  function BasicPlugin() {
    return BasicPlugin.__super__.constructor.apply(this, arguments);
  }

  BasicPlugin.prototype.defaultExt = function() {
    return this.splitExt(this.output)[0];
  };

  BasicPlugin.prototype.renameForFormat = function(entry) {
    var ext0;
    ext0 = entry.ext.pop();
    if (!entry.ext.length) {
      entry.ext.push(this.defaultExt());
    }
    return entry;
  };

  BasicPlugin.prototype.registerPluginOn = function(pluginMap) {
    return pluginMap.addPluginForExtIO(this, this.ext, this.intput, this.output);
  };

  BasicPlugin.prototype.render = function(entry, vars, answerFn) {
    return entry.read(answerFn);
  };

  BasicPlugin.prototype.context = function(entry, callback) {
    return entry.read(callback);
  };

  return BasicPlugin;

})(FilePluginBase);

exports.BasicPlugin = BasicPlugin;

PipelinePlugin = (function(_super) {

  __extends(PipelinePlugin, _super);

  function PipelinePlugin(pluginList) {
    this.pluginList = pluginList;
  }

  PipelinePlugin.prototype.rename = function(entry) {
    var pi, _i, _len, _ref;
    _ref = this.pluginList;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      pi = _ref[_i];
      entry = pi.rename(entry);
    }
    return entry;
  };

  PipelinePlugin.prototype.adapt = function(entry) {
    var self;
    self = Object.create(this);
    self.pluginList = this.pluginList.map(function(pi) {
      return pi.adapt(entry);
    });
    return self;
  };

  PipelinePlugin.prototype.render = function(entry, vars, answerFn) {
    var answerNext, pluginList, renderOverlay;
    pluginList = this.pluginList.slice();
    renderOverlay = function(err, entry_) {
      var pi;
      if (err != null) {
        return answerFn(err);
      } else {
        pi = pluginList.shift();
        pi.render(entry_, vars, answerNext);
      }
    };
    answerNext = function(err, what) {
      if (err != null) {
        return answerFn(err);
      } else if (pluginList.length > 0) {
        try {
          return entry.overlaySource(what, renderOverlay);
        } catch (err) {
          return answerFn(err);
        }
      } else {
        return answerFn.apply(null, arguments);
      }
    };
    return renderOverlay(null, entry, entry.readSync());
  };

  return PipelinePlugin;

})(BasicPlugin);

exports.PipelinePlugin = PipelinePlugin;

StaticPlugin = (function(_super) {

  __extends(StaticPlugin, _super);

  function StaticPlugin() {
    return StaticPlugin.__super__.constructor.apply(this, arguments);
  }

  StaticPlugin.prototype.init = function() {
    var opt, options, _i, _len;
    options = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    this.extList = [];
    for (_i = 0, _len = options.length; _i < _len; _i++) {
      opt = options[_i];
      if (opt.length != null) {
        this.extList.push(splitExt(opt));
      } else {
        this.initOptions(opt);
      }
    }
    return this;
  };

  StaticPlugin.prototype.registerPluginOn = function(pluginMap) {
    var ext, _i, _len, _ref, _results;
    pluginMap.addPluginForExtIO(this, this.ext, this.intput, this.output);
    _ref = this.extList || [];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      ext = _ref[_i];
      if (ext.length === 1) {
        pluginMap.addPluginForKeys(this, ext);
        _results.push(pluginMap.addPluginForKeys(this, ext, '*'));
      } else if (ext.length === 2) {
        _results.push(pluginMap.addPluginForKeys(this, ext.slice(1), ext.slice(0, 1)));
      } else {
        _results.push(console.warn("Ignoreing invalid static extension " + ext));
      }
    }
    return _results;
  };

  StaticPlugin.prototype.render = function(entry, vars, callback) {
    entry.touch(false);
    return callback(null, entry.readStream());
  };

  StaticPlugin.prototype.context = function(entry, callback) {
    return entry.read(callback);
  };

  return StaticPlugin;

})(CombinedPluginBase);

pluginTypes["static"] = StaticPlugin;

exports.StaticPlugin = StaticPlugin;

RenderedPlugin = (function(_super) {

  __extends(RenderedPlugin, _super);

  function RenderedPlugin() {
    return RenderedPlugin.__super__.constructor.apply(this, arguments);
  }

  RenderedPlugin.prototype.rename = BasicPlugin.prototype.renameForFormat;

  RenderedPlugin.prototype.render = function(entry, vars, callback) {
    return this.renderEntry(entry.extendVars(vars), callback);
  };

  RenderedPlugin.prototype.context = function(entry, callback) {
    return this.render(entry, {}, callback);
  };

  RenderedPlugin.prototype.renderEntry = function(entry, vars, callback) {
    var _this = this;
    if (this.renderFile != null) {
      this.renderFile(entry, entry.srcPath, vars, callback);
    } else if (this.render != null) {
      entry.read(function(err, data) {
        if (data != null) {
          return _this.render(entry, data, vars, callback);
        } else {
          return callback(err);
        }
      });
    } else if (this.compileEntry != null) {
      this.compileEntry(entry, vars, function(err, boundRenderFn) {
        if (boundRenderFn != null) {
          return boundRenderFn(vars, callback);
        } else {
          return callback(err);
        }
      });
    } else {
      this.notImplemented('render', entry, callback);
    }
  };

  return RenderedPlugin;

})(BasicPlugin);

pluginTypes.rendered = RenderedPlugin;

exports.RenderedPlugin = RenderedPlugin;

CompiledPlugin = (function(_super) {

  __extends(CompiledPlugin, _super);

  function CompiledPlugin() {
    return CompiledPlugin.__super__.constructor.apply(this, arguments);
  }

  CompiledPlugin.prototype.rename = BasicPlugin.prototype.renameForFormat;

  CompiledPlugin.prototype.context = function(entry, callback) {
    return this.compileEntry(entry, entry.extendVars(), callback);
  };

  CompiledPlugin.prototype.compileEntry = function(entry, vars, callback) {
    var _this = this;
    if (this.compileFile != null) {
      this.compileFile(entry, entry.srcPath, vars, callback);
    } else if (this.compile != null) {
      entry.read(function(err, data) {
        if (data != null) {
          return _this.compile(entry, data, vars, callback);
        } else {
          return callback(err, data);
        }
      });
    } else {
      this.notImplemented('compile', entry, callback);
    }
  };

  return CompiledPlugin;

})(BasicPlugin);

pluginTypes.compiled = CompiledPlugin;

exports.CompiledPlugin = CompiledPlugin;

CompileRenderPlugin = (function(_super) {

  __extends(CompileRenderPlugin, _super);

  function CompileRenderPlugin() {
    return CompileRenderPlugin.__super__.constructor.apply(this, arguments);
  }

  CompileRenderPlugin.prototype.rename = BasicPlugin.prototype.renameForFormat;

  CompileRenderPlugin.prototype.render = RenderedPlugin.prototype.render;

  CompileRenderPlugin.prototype.renderEntry = RenderedPlugin.prototype.renderEntry;

  CompileRenderPlugin.prototype.context = CompiledPlugin.prototype.context;

  CompileRenderPlugin.prototype.compileEntry = CompiledPlugin.prototype.compileEntry;

  return CompileRenderPlugin;

})(BasicPlugin);

pluginTypes.compile_render = CompileRenderPlugin;

exports.CompileRenderPlugin = CompileRenderPlugin;

JsonPlugin = (function(_super) {

  __extends(JsonPlugin, _super);

  function JsonPlugin() {
    return JsonPlugin.__super__.constructor.apply(this, arguments);
  }

  JsonPlugin.prototype.rename = BasicPlugin.prototype.renameForFormat;

  JsonPlugin.prototype.parse = function(entry, callback) {
    return entry.read(function(err, data) {
      if (err != null) {
        return callback(err);
      }
      try {
        return callback(null, JSON.parse(data), data);
      } catch (err) {
        return callback(err, null, data);
      }
    });
  };

  JsonPlugin.prototype.context = function(entry, callback) {
    return this.parse(entry, callback);
  };

  JsonPlugin.prototype.render = function(entry, vars, answerFn) {
    return this.parse(entry, function(err, obj, data) {
      return callback(err, data);
    });
  };

  return JsonPlugin;

})(BasicPlugin);

pluginTypes.json = JsonPlugin;

exports.JsonPlugin = JsonPlugin;

ModulePlugin = (function(_super) {

  __extends(ModulePlugin, _super);

  function ModulePlugin() {
    return ModulePlugin.__super__.constructor.apply(this, arguments);
  }

  ModulePlugin.prototype.rename = BasicPlugin.prototype.renameForFormat;

  ModulePlugin.prototype.adapt = function(entry) {
    var meth, mod, nsMod, self, _i, _len, _ref;
    nsMod = {
      entry: entry,
      host: this
    };
    if (!this.accept(entry, nsMod)) {
      return;
    }
    nsMod.host = self = Object.create(this);
    mod = self.load(entry, nsMod);
    if (mod == null) {
      return;
    }
    _ref = this.pluginProtocol;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      meth = _ref[_i];
      if (mod[meth] != null) {
        self[meth] = mod[meth];
      }
    }
    if (mod.adapt != null) {
      return mod.adapt.call(self, entry);
    } else {
      return self;
    }
  };

  ModulePlugin.prototype.accept = function(entry, nsMod) {
    return !entry.ext.some(function(e) {
      return e.match(/\d/);
    });
  };

  ModulePlugin.prototype.result = function(mod, nsMod) {
    return mod;
  };

  ModulePlugin.prototype.error = function(err, nsMod) {
    console.error("\nModule '" + nsMod.entry.srcRelPath + "' loading encountered an error");
    console.error(err.stack || err);
    return null;
  };

  ModulePlugin.prototype.load = function(entry, nsMod) {
    var mod;
    try {
      mod = entry.loadModule();
      if (mod.initPlugin != null) {
        mod = (typeof mod.initPlugin === "function" ? mod.initPlugin(nsMod) : void 0) || mod;
      }
      return this.result(mod, nsMod);
    } catch (err) {
      return this.error(err, nsMod);
    }
  };

  ModulePlugin.prototype.render = function(entry, vars, answerFn) {
    return this.notImplemented('render', entry, answerFn);
  };

  ModulePlugin.prototype.context = function(entry, callback) {
    return this.notImplemented('context', entry, callback);
  };

  ModulePlugin.prototype.notImplemented = function(protocolMethod, entry, callback) {
    var err;
    err = "Module '" + entry.srcRelPath + "' does not implement `" + protocolMethod + "()`";
    callback(new Error(err));
  };

  return ModulePlugin;

})(BasicPlugin);

pluginTypes.module = ModulePlugin;

exports.ModulePlugin = ModulePlugin;
